### ISSUE TITLE
Text offset

### ISSUE THREAD

**Issue by FreeMasen** [joshka/tui-scrollview#20]
I am trying to use this widget in a TUI application I have been working on but for some reason the `Text` provided to it seems to be offset quite a bit from the edge of the provided `Rect`.

I am not sure if maybe I am misunderstanding how this is supposed to work?

Here is a screenshot of the scroll view offset I am referring to

<img width="820" alt="Screenshot 2024-03-21 at 6 54 41 PM" src="https://github.com/joshka/tui-scrollview/assets/6232026/f3f6511f-0a8d-4824-877a-17053f1bef49">

This code was generated from [this branch](https://github.com/FreeMasen/resume-tui/pull/2) of my project. I am happy to share any other details you'd like.

**Comment by joshka** [comment]
The buffer area inside the scrollview is zero based (i.e. coordinates of the top left corner are 0,0). Your code renders a text field into the area assuming that the coordinate system is the same as the enclosing buffer.

For implementing this view properly, you likely need to:
1. Calculate the total size of the text taking into account wrapping (this is difficult right now, but it's something we want to fix in Ratatui soon)
2. Allocate a Tui-scrollview that matches that size
3. Render the Text to Rect { x: 0, y:0, width, height }

Given that you have a conversion from markdown to Line already, it could be an easier approach to render this directly using a `Paragraph` widget (which supports scrolling that interacts with wrapping).

**Comment by FreeMasen** [comment]
Thank you so much for the reply. I will look to just add a `ScrollBar` to my view. I didn't realize that `Paragraph` did wrapping, so I can stop doing that in the markdown conversion.

Thanks again, this was incredibly helpful!
